GET http://localhost:7799/api/auth

###

POST http://localhost:7799/api/auth/register
Content-Type: application/json

{
    "username": "chicken",
    "password": "123"
}

###
POST http://localhost:7799/api/auth/login
Content-Type: application/json

{
    "username": "lybinh",
    "password": "123123"
}

###
POST http://localhost:7799/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdkNzY0ODI0MmUyZWYzNWYxYzBkNDAiLCJpYXQiOjE2NjkxNjY2NjR9.wFzpl9ybnHPs6ZWfyLVko3ty5c7c_otH42GpBo42KV4

{
    "title": "Catch stick",
    "description": "K'mon, catch it"
}

###
GET http://localhost:7799/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdkNzY0ODI0MmUyZWYzNWYxYzBkNDAiLCJpYXQiOjE2NjkxNjY2NjR9.wFzpl9ybnHPs6ZWfyLVko3ty5c7c_otH42GpBo42KV4

###
PUT http://localhost:7799/api/posts/update/639804fb373ec62924e6f064
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzdkNzY0ODI0MmUyZWYzNWYxYzBkNDAiLCJpYXQiOjE2NjkxNjY2NjR9.wFzpl9ybnHPs6ZWfyLVko3ty5c7c_otH42GpBo42KV4

{
    "title": "Catch stick Updated",
    "description": "K'mon, catch it updated",
    # "url": "https://github.com/plbinh",
    "status": "LEARNED"
}

###
DELETE http://localhost:7799/api/posts/63773a0f112b2702ff3aeac9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzc2ZWVmYTMxZTA5MTQwOTY2NDIwNzgiLCJpYXQiOjE2NjkxNzA4OTd9.fqI02skQKJscu4S5ifO5IMGU-x8Pr1fH2591xFRHP2U
